// Index of scripts in this repo.
// Run: dotnet fsi src/<file>.fsx

printfn "Scripts:"
printfn "01_BindingNotAssignment.fsx"
printfn "02_ExpressionOriented.fsx"
printfn "03_PipelinesAndComposition.fsx"
printfn "04_MatchAndExhaustiveness.fsx"
printfn "05_DiscriminatedUnions.fsx"
printfn "06_IllegalStatesUnrepresentable.fsx"
printfn "07_SingleCaseUnionTypes.fsx"
printfn "08_OptionInsteadOfNull.fsx"
printfn "09_ResultForExpectedErrors.fsx"
printfn "10_ROP_Combinators.fsx"
printfn "11_ResultVsExceptions.fsx"
printfn "12_FunctionalCoreImperativeShell.fsx"
printfn "13_DependencyRejection_Parameterization.fsx"
printfn "14_ReaderMonad_Sketch.fsx"
printfn "15_ActivePatterns.fsx"
printfn "16_UnitsOfMeasure.fsx"
printfn "17_PrintfFormatting.fsx"
printfn "18_MapFilterFold.fsx"
printfn "19_MonoidAggregation.fsx"
printfn "20_CustomOperatorPolicy.fsx"
